"""initial full schema baseline

Revision ID: 8cfc4230cca9
Revises: 
Create Date: 2026-08-24 16:18:23.996229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cfc4230cca9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('covers',
    sa.Column('url_hash', sa.String(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('url_hash')
    )
    op.create_table('ideas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.Column('deleted_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mindmaps',
    sa.Column('url_hash', sa.String(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('mindmap_md', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('url_hash')
    )
    op.create_table('plan_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed_at', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('count', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('tags')
    op.drop_table('plans')
    op.drop_table('plan_nodes')
    op.drop_table('plan_logs')
    op.drop_table('mindmaps')
    op.drop_table('ideas')
    op.drop_table('covers')
    # ### end Alembic commands ###
